
import { GoogleGenAI } from "@google/genai";
import { ToneType } from "../types.ts";

const getSystemInstruction = (tone: ToneType, humanize: boolean) => {
  const toneMap: Record<ToneType, string> = {
    'Professional': 'Corporate and formal. Use precise vocabulary, authoritative syntax, and ensure complete grammatical logic. Ideal for reports and emails.',
    'Friendly': 'Approaching and warm. Natural conversational flow that sounds human and empathetic while remaining polite and polished.',
    'Casual': 'Relaxed and modern. Correct errors but maintain a social, informal vibe. Perfect for texting, chat, and casual social media.',
    'Academic': 'Rigorous and scholarly. Ensure objective tone, complex sentence structures, and high-level vocabulary. Zero colloquialisms permitted.',
    'Standard': 'Balanced and native-level fluent. Fix grammar, spelling, and phrasing while staying as close to the user\'s original style as possible.'
  };

  const humanizePrompt = humanize ? 
    `HUMANIZE PROTOCOL ACTIVE: 
    - Inject natural human-like variation in sentence length and rhythm.
    - Avoid predictable AI patterns, repetitive transitions, and overly formulaic structures.
    - Use subtle linguistic nuances and idiomatic phrasing where appropriate to ensure the text feels authentic and organic.
    - The output must feel like it was typed by a thoughtful human, not generated by a machine.` : '';

  return `You are a world-class Senior Linguistic Editor and AI Writing Expert.
MISSION: Transform the provided text into perfectly fluent, native-level English.

STRICT OPERATIONAL RULES:
1. GRAMMAR: Fix every error in subject-verb agreement, tense, and syntax.
2. ORTHOGRAPHY: Perfect all spelling and punctuation.
3. FLOW: Optimize phrasing for maximum readability and natural flow.
4. TONE: Apply this specific linguistic persona: ${toneMap[tone]}
5. NO CHATTER: Never provide explanations, apologies, or meta-commentary.
6. OUTPUT: Return only the final corrected text. Nothing else.

${humanizePrompt}`;
};

export async function correctText(text: string, tone: ToneType = 'Standard', humanize: boolean = false): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: text,
      config: {
        systemInstruction: getSystemInstruction(tone, humanize),
        temperature: humanize ? 0.7 : 0.1, // Increase temperature for humanized variety
        topP: 0.9,
        topK: 40,
      },
    });

    const resultText = response.text;
    if (!resultText) {
      throw new Error("The AI failed to generate a response. Please try shorter text.");
    }

    return resultText.trim();
  } catch (error: any) {
    console.error("Gemini Edit Error:", error);
    if (error.message?.includes('429')) {
      throw new Error("Rate limit exceeded. Please wait a moment.");
    }
    throw new Error("Connection failed. Check your network and try again.");
  }
}
